import type { CreditCardData } from "@shared/schema";

export const creditCards: CreditCardData[] = [
  {
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "60,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on travel booked through Chase Travel" },
      { category: "dining", multiplier: 3, description: "3x on dining" },
      { category: "online", multiplier: 3, description: "3x on online grocery and streaming" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.0125,
    category: "travel",
  },
  {
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    annualFee: 550,
    signUpBonus: "60,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 10, description: "10x on hotels & car rentals via Chase Travel" },
      { category: "travel", multiplier: 5, description: "5x on flights via Chase Travel" },
      { category: "dining", multiplier: 3, description: "3x on dining" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.015,
    category: "premium-travel",
  },
  {
    name: "Amex Gold Card",
    issuer: "American Express",
    annualFee: 250,
    signUpBonus: "60,000 points after spending $6,000 in 6 months",
    signUpSpendRequirement: 6000,
    signUpTimeframe: 6,
    rewards: [
      { category: "dining", multiplier: 4, description: "4x at restaurants worldwide" },
      { category: "groceries", multiplier: 4, description: "4x at U.S. supermarkets (up to $25k/yr)" },
      { category: "travel", multiplier: 3, description: "3x on flights booked directly" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.02,
    category: "dining-groceries",
  },
  {
    name: "Amex Platinum Card",
    issuer: "American Express",
    annualFee: 695,
    signUpBonus: "80,000 points after spending $8,000 in 6 months",
    signUpSpendRequirement: 8000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on flights booked directly or via Amex Travel" },
      { category: "travel", multiplier: 5, description: "5x on prepaid hotels via Amex Travel" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.02,
    category: "premium-travel",
  },
  {
    name: "Capital One Venture X",
    issuer: "Capital One",
    annualFee: 395,
    signUpBonus: "75,000 miles after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 10, description: "10x on hotels & car rentals via Capital One Travel" },
      { category: "travel", multiplier: 5, description: "5x on flights via Capital One Travel" },
      { category: "other", multiplier: 2, description: "2x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "premium-travel",
  },
  {
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    annualFee: 95,
    signUpBonus: "75,000 miles after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on hotels & car rentals via Capital One Travel" },
      { category: "other", multiplier: 2, description: "2x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "Citi Double Cash",
    issuer: "Citi",
    annualFee: 0,
    signUpBonus: "$200 back after spending $1,500 in 6 months",
    signUpSpendRequirement: 1500,
    signUpTimeframe: 6,
    rewards: [
      { category: "other", multiplier: 2, description: "2% on every purchase (1% when you buy + 1% when you pay)" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 5, description: "5% on travel via Chase Travel" },
      { category: "dining", multiplier: 3, description: "3% on dining and drugstores" },
      { category: "other", multiplier: 1.5, description: "1.5% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Amex Blue Cash Preferred",
    issuer: "American Express",
    annualFee: 95,
    signUpBonus: "$250 back after spending $3,000 in 6 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 6,
    rewards: [
      { category: "groceries", multiplier: 6, description: "6% at U.S. supermarkets (up to $6k/yr)" },
      { category: "online", multiplier: 6, description: "6% on select streaming services" },
      { category: "gas", multiplier: 3, description: "3% at U.S. gas stations" },
      { category: "travel", multiplier: 3, description: "3% on transit" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "groceries",
  },
  {
    name: "Discover it Cash Back",
    issuer: "Discover",
    annualFee: 0,
    signUpBonus: "Cashback Match: all cash back earned in first year is matched",
    signUpSpendRequirement: 0,
    signUpTimeframe: 12,
    rewards: [
      { category: "rotating", multiplier: 5, description: "5% on rotating quarterly categories (up to $1,500)" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Wells Fargo Active Cash",
    issuer: "Wells Fargo",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "other", multiplier: 2, description: "2% on all purchases" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Capital One SavorOne",
    issuer: "Capital One",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "dining", multiplier: 3, description: "3% on dining and entertainment" },
      { category: "groceries", multiplier: 3, description: "3% on grocery stores" },
      { category: "online", multiplier: 3, description: "3% on streaming services" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "dining-groceries",
  },
  {
    name: "Chase Ink Business Preferred",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "100,000 points after spending $8,000 in 3 months",
    signUpSpendRequirement: 8000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 3, description: "3x on travel and select business categories" },
      { category: "online", multiplier: 3, description: "3x on internet, cable, and phone services" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.0125,
    category: "business",
  },
  {
    name: "Hilton Honors Amex Surpass",
    issuer: "American Express",
    annualFee: 150,
    signUpBonus: "130,000 Hilton points after spending $3,000 in 6 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 12, description: "12x at hotels in the Hilton portfolio" },
      { category: "dining", multiplier: 6, description: "6x at restaurants, supermarkets, and gas stations" },
      { category: "groceries", multiplier: 6, description: "6x at U.S. supermarkets" },
      { category: "gas", multiplier: 6, description: "6x at U.S. gas stations" },
      { category: "other", multiplier: 3, description: "3x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.005,
    category: "hotel",
  },
  {
    name: "United Explorer Card",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "60,000 miles after spending $3,000 in 3 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 2, description: "2x on United purchases, dining, and hotel stays" },
      { category: "dining", multiplier: 2, description: "2x on dining" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.012,
    category: "airline",
  },
];
