import type { CreditCardData } from "@shared/schema";

export const creditCards: CreditCardData[] = [
  {
    name: "Chase Sapphire Preferred",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "60,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on travel booked through Chase Travel" },
      { category: "dining", multiplier: 3, description: "3x on dining" },
      { category: "online", multiplier: 3, description: "3x on online grocery and streaming" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.0125,
    category: "travel",
  },
  {
    name: "Chase Sapphire Reserve",
    issuer: "Chase",
    annualFee: 550,
    signUpBonus: "60,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 10, description: "10x on hotels & car rentals via Chase Travel" },
      { category: "travel", multiplier: 5, description: "5x on flights via Chase Travel" },
      { category: "dining", multiplier: 3, description: "3x on dining" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.015,
    category: "premium-travel",
  },
  {
    name: "Chase Freedom Unlimited",
    issuer: "Chase",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 5, description: "5% on travel via Chase Travel" },
      { category: "dining", multiplier: 3, description: "3% on dining and drugstores" },
      { category: "other", multiplier: 1.5, description: "1.5% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Chase Freedom Flex",
    issuer: "Chase",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "rotating", multiplier: 5, description: "5% on rotating quarterly categories (up to $1,500)" },
      { category: "travel", multiplier: 5, description: "5% on travel via Chase Travel" },
      { category: "dining", multiplier: 3, description: "3% on dining and drugstores" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Chase Ink Business Preferred",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "100,000 points after spending $8,000 in 3 months",
    signUpSpendRequirement: 8000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 3, description: "3x on travel and select business categories" },
      { category: "online", multiplier: 3, description: "3x on internet, cable, and phone services" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.0125,
    category: "business",
  },
  {
    name: "Amex Gold Card",
    issuer: "American Express",
    annualFee: 250,
    signUpBonus: "60,000 points after spending $6,000 in 6 months",
    signUpSpendRequirement: 6000,
    signUpTimeframe: 6,
    rewards: [
      { category: "dining", multiplier: 4, description: "4x at restaurants worldwide" },
      { category: "groceries", multiplier: 4, description: "4x at U.S. supermarkets (up to $25k/yr)" },
      { category: "travel", multiplier: 3, description: "3x on flights booked directly" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.02,
    category: "dining-groceries",
  },
  {
    name: "Amex Platinum Card",
    issuer: "American Express",
    annualFee: 695,
    signUpBonus: "80,000 points after spending $8,000 in 6 months",
    signUpSpendRequirement: 8000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on flights booked directly or via Amex Travel" },
      { category: "travel", multiplier: 5, description: "5x on prepaid hotels via Amex Travel" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.02,
    category: "premium-travel",
  },
  {
    name: "Amex Green Card",
    issuer: "American Express",
    annualFee: 150,
    signUpBonus: "40,000 points after spending $3,000 in 6 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 3, description: "3x on travel including flights, hotels, and transit" },
      { category: "dining", multiplier: 3, description: "3x at restaurants worldwide" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.02,
    category: "travel",
  },
  {
    name: "Amex Blue Cash Preferred",
    issuer: "American Express",
    annualFee: 95,
    signUpBonus: "$250 back after spending $3,000 in 6 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 6,
    rewards: [
      { category: "groceries", multiplier: 6, description: "6% at U.S. supermarkets (up to $6k/yr)" },
      { category: "online", multiplier: 6, description: "6% on select streaming services" },
      { category: "gas", multiplier: 3, description: "3% at U.S. gas stations" },
      { category: "travel", multiplier: 3, description: "3% on transit" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "groceries",
  },
  {
    name: "Amex Blue Cash Everyday",
    issuer: "American Express",
    annualFee: 0,
    signUpBonus: "$200 back after spending $2,000 in 6 months",
    signUpSpendRequirement: 2000,
    signUpTimeframe: 6,
    rewards: [
      { category: "groceries", multiplier: 3, description: "3% at U.S. supermarkets (up to $6k/yr)" },
      { category: "online", multiplier: 3, description: "3% at U.S. online retail purchases" },
      { category: "gas", multiplier: 3, description: "3% at U.S. gas stations" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Amex Business Gold",
    issuer: "American Express",
    annualFee: 375,
    signUpBonus: "70,000 points after spending $10,000 in 3 months",
    signUpSpendRequirement: 10000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 4, description: "4x on the 2 categories where you spend the most each month" },
      { category: "dining", multiplier: 4, description: "4x at U.S. restaurants" },
      { category: "gas", multiplier: 4, description: "4x at U.S. gas stations" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.02,
    category: "business",
  },
  {
    name: "Capital One Venture X",
    issuer: "Capital One",
    annualFee: 395,
    signUpBonus: "75,000 miles after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 10, description: "10x on hotels & car rentals via Capital One Travel" },
      { category: "travel", multiplier: 5, description: "5x on flights via Capital One Travel" },
      { category: "other", multiplier: 2, description: "2x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "premium-travel",
  },
  {
    name: "Capital One Venture Rewards",
    issuer: "Capital One",
    annualFee: 95,
    signUpBonus: "75,000 miles after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on hotels & car rentals via Capital One Travel" },
      { category: "other", multiplier: 2, description: "2x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "Capital One Savor Rewards",
    issuer: "Capital One",
    annualFee: 95,
    signUpBonus: "$300 bonus after spending $3,000 in 3 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 3,
    rewards: [
      { category: "dining", multiplier: 4, description: "4% on dining and entertainment" },
      { category: "groceries", multiplier: 3, description: "3% at grocery stores" },
      { category: "online", multiplier: 3, description: "3% on streaming services" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "dining-groceries",
  },
  {
    name: "Capital One SavorOne",
    issuer: "Capital One",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "dining", multiplier: 3, description: "3% on dining and entertainment" },
      { category: "groceries", multiplier: 3, description: "3% on grocery stores" },
      { category: "online", multiplier: 3, description: "3% on streaming services" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "dining-groceries",
  },
  {
    name: "Capital One Quicksilver",
    issuer: "Capital One",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "other", multiplier: 1.5, description: "1.5% cash back on every purchase" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Citi Double Cash",
    issuer: "Citi",
    annualFee: 0,
    signUpBonus: "$200 back after spending $1,500 in 6 months",
    signUpSpendRequirement: 1500,
    signUpTimeframe: 6,
    rewards: [
      { category: "other", multiplier: 2, description: "2% on every purchase (1% when you buy + 1% when you pay)" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Citi Premier",
    issuer: "Citi",
    annualFee: 95,
    signUpBonus: "60,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 3, description: "3x on air travel and hotels" },
      { category: "dining", multiplier: 3, description: "3x at restaurants" },
      { category: "groceries", multiplier: 3, description: "3x at supermarkets" },
      { category: "gas", multiplier: 3, description: "3x at gas stations" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "Citi Custom Cash",
    issuer: "Citi",
    annualFee: 0,
    signUpBonus: "$200 back after spending $1,500 in 6 months",
    signUpSpendRequirement: 1500,
    signUpTimeframe: 6,
    rewards: [
      { category: "groceries", multiplier: 5, description: "5% on your top eligible spend category each billing cycle (up to $500)" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Citi Strata Premier",
    issuer: "Citi",
    annualFee: 95,
    signUpBonus: "75,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 10, description: "10x on hotels and car rentals via thankyou.com" },
      { category: "dining", multiplier: 3, description: "3x at restaurants and supermarkets" },
      { category: "groceries", multiplier: 3, description: "3x at supermarkets" },
      { category: "gas", multiplier: 3, description: "3x at gas stations" },
      { category: "travel", multiplier: 3, description: "3x on air travel and other travel" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "Discover it Cash Back",
    issuer: "Discover",
    annualFee: 0,
    signUpBonus: "Cashback Match: all cash back earned in first year is matched",
    signUpSpendRequirement: 0,
    signUpTimeframe: 12,
    rewards: [
      { category: "rotating", multiplier: 5, description: "5% on rotating quarterly categories (up to $1,500)" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Wells Fargo Active Cash",
    issuer: "Wells Fargo",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $500 in 3 months",
    signUpSpendRequirement: 500,
    signUpTimeframe: 3,
    rewards: [
      { category: "other", multiplier: 2, description: "2% on all purchases" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Wells Fargo Autograph",
    issuer: "Wells Fargo",
    annualFee: 0,
    signUpBonus: "20,000 points after spending $1,000 in 3 months",
    signUpSpendRequirement: 1000,
    signUpTimeframe: 3,
    rewards: [
      { category: "dining", multiplier: 3, description: "3x on restaurants" },
      { category: "travel", multiplier: 3, description: "3x on travel" },
      { category: "gas", multiplier: 3, description: "3x on gas stations" },
      { category: "online", multiplier: 3, description: "3x on streaming services" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "Bank of America Customized Cash",
    issuer: "Bank of America",
    annualFee: 0,
    signUpBonus: "$200 bonus after spending $1,000 in 3 months",
    signUpSpendRequirement: 1000,
    signUpTimeframe: 3,
    rewards: [
      { category: "groceries", multiplier: 3, description: "3% in your choice category (gas, online shopping, dining, travel, drug stores, or home improvement)" },
      { category: "groceries", multiplier: 2, description: "2% at grocery stores and wholesale clubs" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Bank of America Premium Rewards",
    issuer: "Bank of America",
    annualFee: 95,
    signUpBonus: "60,000 points after spending $4,000 in 3 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 2, description: "2x on travel and dining" },
      { category: "dining", multiplier: 2, description: "2x on dining" },
      { category: "other", multiplier: 1.5, description: "1.5x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "US Bank Altitude Go",
    issuer: "US Bank",
    annualFee: 0,
    signUpBonus: "$250 bonus after spending $1,000 in 3 months",
    signUpSpendRequirement: 1000,
    signUpTimeframe: 3,
    rewards: [
      { category: "dining", multiplier: 4, description: "4x on dining" },
      { category: "groceries", multiplier: 2, description: "2x on grocery stores, grocery delivery, and streaming" },
      { category: "online", multiplier: 2, description: "2x on streaming services" },
      { category: "gas", multiplier: 2, description: "2x at gas stations and EV charging" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "dining-groceries",
  },
  {
    name: "US Bank Altitude Connect",
    issuer: "US Bank",
    annualFee: 95,
    signUpBonus: "50,000 points after spending $2,000 in 4 months",
    signUpSpendRequirement: 2000,
    signUpTimeframe: 4,
    rewards: [
      { category: "travel", multiplier: 5, description: "5x on prepaid hotels and car rentals via Altitude Rewards Center" },
      { category: "travel", multiplier: 4, description: "4x on travel and mobile wallet purchases" },
      { category: "dining", multiplier: 2, description: "2x on dining, gas stations, and streaming" },
      { category: "gas", multiplier: 2, description: "2x at gas stations" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "travel",
  },
  {
    name: "Marriott Bonvoy Boundless",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "3 free night awards (each worth up to 50,000 points) after spending $3,000 in 3 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 6, description: "6x at Marriott hotels" },
      { category: "groceries", multiplier: 2, description: "2x on groceries, dining, and gas" },
      { category: "dining", multiplier: 2, description: "2x on dining" },
      { category: "gas", multiplier: 2, description: "2x at gas stations" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.008,
    category: "hotel",
  },
  {
    name: "World of Hyatt Credit Card",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "30,000 bonus points after spending $3,000 in 3 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 4, description: "4x at Hyatt hotels" },
      { category: "dining", multiplier: 2, description: "2x on dining, airline tickets, and local transit" },
      { category: "travel", multiplier: 2, description: "2x on airline tickets and local transit" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.017,
    category: "hotel",
  },
  {
    name: "Hilton Honors Amex Surpass",
    issuer: "American Express",
    annualFee: 150,
    signUpBonus: "130,000 Hilton points after spending $3,000 in 6 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 12, description: "12x at hotels in the Hilton portfolio" },
      { category: "dining", multiplier: 6, description: "6x at restaurants" },
      { category: "groceries", multiplier: 6, description: "6x at U.S. supermarkets" },
      { category: "gas", multiplier: 6, description: "6x at U.S. gas stations" },
      { category: "other", multiplier: 3, description: "3x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.005,
    category: "hotel",
  },
  {
    name: "Delta SkyMiles Gold",
    issuer: "American Express",
    annualFee: 150,
    signUpBonus: "40,000 miles after spending $3,000 in 6 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 2, description: "2x on Delta purchases" },
      { category: "dining", multiplier: 2, description: "2x at restaurants" },
      { category: "groceries", multiplier: 2, description: "2x at U.S. supermarkets" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.012,
    category: "airline",
  },
  {
    name: "Delta SkyMiles Platinum",
    issuer: "American Express",
    annualFee: 350,
    signUpBonus: "90,000 miles after spending $4,000 in 6 months",
    signUpSpendRequirement: 4000,
    signUpTimeframe: 6,
    rewards: [
      { category: "travel", multiplier: 3, description: "3x on Delta purchases" },
      { category: "dining", multiplier: 2, description: "2x at restaurants" },
      { category: "groceries", multiplier: 2, description: "2x at U.S. supermarkets" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.012,
    category: "airline",
  },
  {
    name: "United Explorer Card",
    issuer: "Chase",
    annualFee: 95,
    signUpBonus: "60,000 miles after spending $3,000 in 3 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 2, description: "2x on United purchases, dining, and hotel stays" },
      { category: "dining", multiplier: 2, description: "2x on dining" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.012,
    category: "airline",
  },
  {
    name: "Southwest Rapid Rewards Plus",
    issuer: "Chase",
    annualFee: 69,
    signUpBonus: "50,000 points after spending $1,000 in 3 months",
    signUpSpendRequirement: 1000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 2, description: "2x on Southwest purchases" },
      { category: "travel", multiplier: 2, description: "2x on Rapid Rewards hotel and car rental partners" },
      { category: "dining", multiplier: 1, description: "1x on dining" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.014,
    category: "airline",
  },
  {
    name: "Southwest Rapid Rewards Priority",
    issuer: "Chase",
    annualFee: 149,
    signUpBonus: "50,000 points after spending $1,000 in 3 months",
    signUpSpendRequirement: 1000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 3, description: "3x on Southwest purchases" },
      { category: "travel", multiplier: 2, description: "2x on Rapid Rewards hotel and car rental partners" },
      { category: "dining", multiplier: 2, description: "2x on dining and local transit" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.014,
    category: "airline",
  },
  {
    name: "Apple Card",
    issuer: "Goldman Sachs",
    annualFee: 0,
    signUpBonus: "No traditional sign-up bonus",
    signUpSpendRequirement: 0,
    signUpTimeframe: 0,
    rewards: [
      { category: "other", multiplier: 2, description: "2% on all Apple Pay purchases" },
      { category: "other", multiplier: 1, description: "1% on purchases with physical card" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Amazon Prime Visa",
    issuer: "Chase",
    annualFee: 0,
    signUpBonus: "$200 Amazon gift card upon approval",
    signUpSpendRequirement: 0,
    signUpTimeframe: 0,
    rewards: [
      { category: "online", multiplier: 5, description: "5% back at Amazon.com and Whole Foods (with Prime)" },
      { category: "travel", multiplier: 2, description: "2% at restaurants, gas stations, and drugstores" },
      { category: "dining", multiplier: 2, description: "2% at restaurants" },
      { category: "gas", multiplier: 2, description: "2% at gas stations" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: true,
    pointValue: 0.01,
    category: "online",
  },
  {
    name: "IHG One Rewards Premier",
    issuer: "Chase",
    annualFee: 99,
    signUpBonus: "140,000 bonus points after spending $3,000 in 3 months",
    signUpSpendRequirement: 3000,
    signUpTimeframe: 3,
    rewards: [
      { category: "travel", multiplier: 26, description: "26x at IHG hotels (10x base + 16x bonus)" },
      { category: "travel", multiplier: 5, description: "5x on travel, dining, and gas" },
      { category: "dining", multiplier: 5, description: "5x at restaurants" },
      { category: "gas", multiplier: 5, description: "5x at gas stations" },
      { category: "other", multiplier: 1, description: "1x on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.005,
    category: "hotel",
  },
  {
    name: "Costco Anywhere Visa",
    issuer: "Citi",
    annualFee: 0,
    signUpBonus: "No traditional sign-up bonus",
    signUpSpendRequirement: 0,
    signUpTimeframe: 0,
    rewards: [
      { category: "gas", multiplier: 4, description: "4% on eligible gas (up to $7k/yr)" },
      { category: "travel", multiplier: 3, description: "3% on travel and restaurants" },
      { category: "dining", multiplier: 3, description: "3% at restaurants" },
      { category: "groceries", multiplier: 2, description: "2% at Costco and Costco.com" },
      { category: "other", multiplier: 1, description: "1% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "PayPal Cashback Mastercard",
    issuer: "Synchrony",
    annualFee: 0,
    signUpBonus: "No traditional sign-up bonus",
    signUpSpendRequirement: 0,
    signUpTimeframe: 0,
    rewards: [
      { category: "other", multiplier: 3, description: "3% on PayPal purchases" },
      { category: "other", multiplier: 2, description: "2% on everything else" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.01,
    category: "cash-back",
  },
  {
    name: "Bilt Mastercard",
    issuer: "Wells Fargo",
    annualFee: 0,
    signUpBonus: "No traditional sign-up bonus (points on rent day 1)",
    signUpSpendRequirement: 0,
    signUpTimeframe: 0,
    rewards: [
      { category: "dining", multiplier: 3, description: "3x on dining" },
      { category: "travel", multiplier: 2, description: "2x on travel" },
      { category: "other", multiplier: 1, description: "1x on rent and everything else (up to 100k pts/yr on rent)" },
    ],
    noForeignTransactionFee: false,
    pointValue: 0.018,
    category: "travel",
  },
];
